---
name: Macos Apple-Clang

on: [push, workflow_dispatch]

env:
  CONAN_UPLOAD: ${{ secrets.CONAN_URL }}
  CONAN_PASSWORD_SINTEF: ${{ secrets.CONAN_PASSWORD }}
  CONAN_LOGIN_USERNAME_SINTEF: ${{ secrets.CONAN_USER }}
  CONFIG_URL: https://github.com/sintef-ocean/conan-configs.git

jobs:
  conan-with-applw-clang:
    name: Conan
    runs-on: macos-latest
    env:
      USER_CHANNEL: "${{ matrix.conan == '1.0' && 'sintef/stable' || '--user sintef --channel stable' }}"
      UPLOAD_FLAGS: "${{ matrix.conan == '1.0' && '--all' || '' }}"
      cppstd: "${{ matrix.compiler_version < 15 && 'gnu14' || 'gnu17' }}"
    strategy:
      fail-fast: false
      matrix:
        conan: ["1.0", "2.0"]
        profile: [apple_clang]
        compiler_version: [14]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: |
          pip3 install --upgrade setuptools pip
          pip3 install --upgrade conan~=${{ matrix.conan }}
      - name: Configure Conan
        run: conan remote add sintef ${CONAN_UPLOAD}
      - name: Get package name Conan 1
        if: matrix.conan == '1.0'
        run: echo "package_name=$(conan inspect --raw name .)" >> $GITHUB_ENV
      - name: Get package name Conan 2
        if: matrix.conan == '2.0'
        run: echo "package_name=$(conan inspect -f json . | jq .name -r)" >> $GITHUB_ENV
      - name: Conan create
        run: |
          git config --global --add safe.directory '*'
          conan config install ${{ env.CONFIG_URL }}  --type git -sf conan${{ matrix.conan }}
          conan config install ${{ env.CONFIG_URL }}  --type git -sf profiles -tf profiles
          conan create -s build_type=${{ matrix.build_type }} \
            -s compiler.version=${{ matrix.compiler_version }} \
            -s compiler.cppstd=${{ env.cppstd }} \
            -pr:b=${{ matrix.profile }} -pr:h=${{ matrix.profile }} \
            -b missing -b outdated -b ${{ env.package_name }}* \
            . ${{ env.USER_CHANNEL }}
      - name: Conan upload
        run: conan upload --confirm -r sintef ${{ env.package_name }}* --force ${{ env.UPLOAD_FLAGS }}
